/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import static com.sun.corba.se.impl.presentation.rmi.StubConnectImpl.connect;
import config.Session;
import config.dbConnect;
import config.passwordHasher;
import customeragentgui.login;
import static customeragentgui.registration.username;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.management.remote.JMXConnectorFactory.connect;
import static javax.rmi.PortableRemoteObject.connect;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class changePass extends javax.swing.JFrame {

    
    public changePass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        acc_ln2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nvg1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        iddisplay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oldpass = new javax.swing.JTextField();
        newpass = new javax.swing.JTextField();
        conpass = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        acc_ln1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        acc_ln3 = new javax.swing.JLabel();
        nvg = new javax.swing.JPanel();
        acc_fn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        acc_ln = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(null);

        acc_ln2.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        acc_ln2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ln2.setText("Save");
        jPanel3.add(acc_ln2);
        acc_ln2.setBounds(10, 0, 80, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nvg1.setBackground(new java.awt.Color(0, 0, 0));
        nvg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGOUT");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        nvg1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 180, 50));

        iddisplay.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        iddisplay.setForeground(new java.awt.Color(255, 255, 255));
        iddisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iddisplay.setText("(UID)");
        nvg1.add(iddisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 170, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHANGE PASSWORD");
        nvg1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 50));

        jPanel1.add(nvg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        oldpass.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        oldpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oldpass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Type Old Pass", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N
        oldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpassActionPerformed(evt);
            }
        });
        jPanel1.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 270, 40));

        newpass.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        newpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newpass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Enter New Pass", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 270, 40));

        conpass.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        conpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        conpass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Confirm password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N
        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        jPanel1.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 270, 40));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        acc_ln1.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        acc_ln1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ln1.setText("Back");
        jPanel2.add(acc_ln1);
        acc_ln1.setBounds(10, 0, 80, 30);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 100, 30));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        acc_ln3.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        acc_ln3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ln3.setText("Save");
        jPanel4.add(acc_ln3);
        acc_ln3.setBounds(10, 0, 80, 30);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 670, 520));

        nvg.setBackground(new java.awt.Color(0, 0, 0));
        nvg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_fn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        acc_fn.setForeground(new java.awt.Color(255, 255, 255));
        acc_fn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_fn.setText("USER");
        nvg.add(acc_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-80-removebg-preview.png"))); // NOI18N
        nvg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 80, 100));

        acc_ln.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        acc_ln.setForeground(new java.awt.Color(255, 255, 255));
        acc_ln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ln.setText("USER");
        nvg.add(acc_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 40));

        getContentPane().add(nvg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       login loginScreen = new login(); 
        JOptionPane.showMessageDialog(null, "LOG-OUT!");
        loginScreen.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         Session sess = Session.getInstance();
         iddisplay.setText("USER ID:"+sess.getUid());
        
       
       
       
        
    }//GEN-LAST:event_formWindowActivated

    private void oldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpassActionPerformed

    }//GEN-LAST:event_oldpassActionPerformed

    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
      
      try {
    dbConnect dbc = new dbConnect();
    Session sess = Session.getInstance();
    String oldbpass; 

    
    String query = "SELECT u_password1 FROM users WHERE u_id = ?";
    PreparedStatement pstmt = dbc.getPreparedStatement(query);
    pstmt.setInt(1, sess.getUid()); 
    ResultSet rs = pstmt.executeQuery();

    if (rs.next()) {
        oldbpass = rs.getString("u_password1"); 
        String oldhash = passwordHasher.hashPassword(oldpass.getText()); 
        String newPassword = newpass.getText(); 
        String confirmPassword = conpass.getText(); 

     
        if (!oldbpass.equals(oldhash)) {
            JOptionPane.showMessageDialog(null, "Old password is incorrect!");
            return; 
        }

        
        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "New Password and Confirm Password do not match!");
            return; 
        }

     
        String npassHash = passwordHasher.hashPassword(newPassword); 
        String updateQuery = "UPDATE users SET u_password1 = ? WHERE u_id = ?";
        PreparedStatement updateStmt = dbc.getPreparedStatement(updateQuery);
        updateStmt.setString(1, npassHash);
        updateStmt.setInt(2, sess.getUid());

        int rowsUpdated = updateStmt.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Password updated successfully!");
            login lg = new login();
            lg.setVisible(true);
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(null, "Error updating password. Please try again.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "User not found!");
    }
} catch (SQLException | NoSuchAlgorithmException ex) {
    ex.printStackTrace(); 
    JOptionPane.showMessageDialog(null, "An error occurred. Please try again.");
}

    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_fn;
    private javax.swing.JLabel acc_ln;
    private javax.swing.JLabel acc_ln1;
    private javax.swing.JLabel acc_ln2;
    private javax.swing.JLabel acc_ln3;
    private javax.swing.JTextField conpass;
    private javax.swing.JLabel iddisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField newpass;
    private javax.swing.JPanel nvg;
    private javax.swing.JPanel nvg1;
    private javax.swing.JTextField oldpass;
    // End of variables declaration//GEN-END:variables
}
