
package customeragentgui;
import admin.adminDashboard;
import user.userdashboard;
import config.Session;
import config.dbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }   
        static String status;
        static String type;
       public static boolean loginAcc(String username, String password){
        dbConnect connect = new dbConnect();
        
        try{
            String query = "SELECT * FROM users  WHERE u_usname = '" + username + "' AND u_password1 = '" + password + "'";
            ResultSet resultSet = connect.getData(query);
           if(resultSet.next()){
               status = resultSet.getString("u_status");
               type = resultSet.getString("u_ty");
                   Session sess= Session.getInstance();
                  sess.setUid(resultSet.getInt("u_id"));
                  sess.setFname(resultSet.getString("u_fname"));
                  sess.setLname(resultSet.getString("u_lname"));
                  sess.setEmail(resultSet.getString("u_email"));
                  sess.setTy(resultSet.getString("u_ty"));
                  sess.setUsername(resultSet.getString("u_usname"));
                  sess.setStatus(resultSet.getString("u_status"));
 
               return true;
           }else{
               return false;
           }
        }catch (SQLException ex) {
            return false;
        }

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        nvg = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        fjpassword = new javax.swing.JPasswordField();
        reg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(51, 0, 153));
        jDesktopPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nvg.setBackground(new java.awt.Color(255, 255, 255));
        nvg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Form", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Wide Latin", 2, 48))); // NOI18N
        nvg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(0, 153, 0));
        login.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        login.setText("Log in");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        nvg.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, 30));

        cancel.setBackground(new java.awt.Color(255, 51, 51));
        cancel.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        nvg.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password:");
        nvg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Username:");
        nvg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, 20));

        username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        nvg.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, 30));

        fjpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nvg.add(fjpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, 30));

        reg.setBackground(new java.awt.Color(0, 153, 0));
        reg.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        reg.setText("New user? Click Here to register?");
        reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regMouseClicked(evt);
            }
        });
        nvg.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 240, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deee-removebg-preview (1).png"))); // NOI18N
        nvg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 140, 100));

        jDesktopPane1.add(nvg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 380));

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 840, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseClicked
        registration rf = new registration();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if(loginAcc(username.getText(),fjpassword.getText())){
            if(!status.equals("Active")){
                JOptionPane.showMessageDialog(null,"In-Active Account, Contact the Admin!");
            }else{
                JOptionPane.showMessageDialog(null,"Login Success!");
                if(type.equals("Admin")){
                    adminDashboard ads=new adminDashboard();
                    ads.setVisible(true);
                    this.dispose();
                }else if(type.equals("User")){
                    userdashboard usd = new userdashboard();
                    usd.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"No Account type found, Contact the Admin");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Login Failed!");

        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField fjpassword;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPanel nvg;
    private javax.swing.JLabel reg;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
